config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'memos#index'
  # root 'home#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/mypage', to: 'users#me'
  resources :users, only: %i[new create]
  resources :memos

  get '/category/:id', to: 'categories#show'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: categories
#
#  id         :bigint           not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Category < ApplicationRecord
  has_many :memos
end

app/models/memo.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: memos
#
#  id          :bigint           not null, primary key
#  body        :string(255)
#  picture     :string(255)
#  title       :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#
class Memo < ApplicationRecord
  belongs_to :category
  mount_uploader :picture, PictureUploader

  validates :title, presence: true, length: { maximum: 12 }
  validates :body, presence: true, length: { maximum: 100 }
  validate :picture_size

  private

  def picture_size
    errors.add(:picture, 'ファイルサイズを5MB以下にしてください') if picture.size > 5.megabytes
  end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string(255)      not null
#  name            :string(255)      not null
#  password_digest :string(255)      not null
#  remember_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord
  attr_accessor :remember_token
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  before_validation { email.downcase! }

  validates :name,
            presence: true,
            length: { maximum: 20 }
  validates :email,
            presence: true,
            uniqueness: true,
            length: { maximum: 255 },
            format: {
              with: VALID_EMAIL_REGEX,
              message: ' は正しい形式で入力してください'
            }
  validates :password,
            length: { minimum: 8 }

  has_secure_password

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :current_user
  before_action :get_category

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])

    # return unless session[:user_id]
    # @current_user = User.find_by(id: session[:user_id])
  end

  def get_category
    @categories = Category.all
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def show
    @memos = Memo.where(category_id: params[:id])
    @category = Category.find(params[:id])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/memos_controller.rb
# frozen_string_literal: true

class MemosController < ApplicationController
  before_action :set_target_memo, only: %i[edit update destroy]

  def index
    @memos = Memo.all
  end

  def new
    @memo = Memo.new(flash[:memo])
  end

  def create
    memo = Memo.new(memo_params)
    if memo.save
      flash[:success] = "「#{memo.title}」のメモを作成しました"
      redirect_to root_path
    else
      redirect_to new_memo_path, flash: {
        memo: memo,
        error_messages: memo.errors.full_messages
      }
    end
  end

  def destroy
    @memo.destroy
    redirect_to root_path, flash: { success: "「#{@memo.title}」のメモが削除されました" }
  end

  def edit; end

  def update
    if @memo.update(memo_params)
      flash[:success] = "「#{@memo.title}」のメモを編集しました"
      redirect_to root_path
    else
      redirect_back fallback_location: root_path, flash: {
        user: @memo,
        error_messages: @memo.errors.full_messages
      }
    end
  end

  private

  # ストロングパラメータ
  def memo_params
    params.require(:memo).permit(:title, :body, :category_id, :picture)
  end

  def set_target_memo
    @memo = Memo.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email])
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      remember user
      flash[:success] = 'ログインしました'
      redirect_to mypage_path
    else
      # flash[:success].now = "ログインに失敗しました"
      render :new
      # redirect_back fallback_location: root_path
      # パスワードが正しくありませんなど
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:success] = 'ログアウトしました'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new(flash[:user])
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to mypage_path
    else
      redirect_back fallback_location: root_path, flash: {
        user: user,
        error_messages: user.errors.full_messages
      }
    end
  end

  def me; end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def header_link_item(name, path)
    class_name = 'nav-item'
    class_name << ' active' if current_page?(path)

    content_tag :li, class: class_name do
      link_to name, path, class: 'nav-link'
    end
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/memos_helper.rb
# frozen_string_literal: true

module MemosHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/application/_footer.html.erb
<footer class="footer">
  <p class="footer__item">&copy; 2020 Memo App</p>
</footer>

app/views/application/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Memo App</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= header_link_item('ホーム', root_path) %></li>
        <li><%= header_link_item('メモ一覧', memos_path) %></li>
        <li><%= header_link_item('新規メモ', new_memo_path) %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @categories.each do |category| %>
              <li><a href="/category/<%= category.id %>"><%= category.name %></a></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">検索</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <% if @current_user %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%=@current_user.name%> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'マイページ', mypage_path, class: 'dropdown-item' %></li>
              <li><%= link_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-item' %></>
            </ul>
          <% else %>
            <ul class="nav navbar-nav">
              <li><%= header_link_item('ログイン', login_path) %></li>
              <li><%= header_link_item('登録', new_user_path) %></li>
            </ul>
          <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/categories/show.html.erb
<h3><%= @category.name %>'s Memo List</h3>
<% @memos.each do |memo| %>
  <div class="col-sm-4">
    <div class="panel panel-warning">
      <div class="panel-heading">
        <h4 class="panel-title"><%= memo.title %></h4>
        <p><%= memo.category.name %></p>

        <div class="buttons">
          <a href="/memos/<%= memo.id %>/edit"><span class="glyphicon glyphicon-edit"></span></a>
          <a href="/memos/<%= memo.id %>" data-method="delete"><span class="glyphicon glyphicon-trash"></span></a>
        </div>
      </div>
      <div class="panel-body">
        <%= memo.body %>
      </div>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'header' %>
    <main>
      <% flash.each do |message_type, message| %>
        <% if message_type == 'success' %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      <% end %>
      <%= yield %>
    </main>
    <%= render 'footer' %>
  </body>
</html>

app/views/memos/_form.html.erb
<br/>
<%= render 'shared/error_messages' %>

<%= form_with model: memo do |f| %>
  <div class='form-group'>
    <%= f.label :title, 'タイトル' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :body, '本文' %>
    <%= f.text_field :body, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :category_id, 'カテゴリー' %>
    <%= f.select :category_id, Category.all.map { |category| [category.name, category.id] }, {} , { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.label :picture, '画像ファイル' %>
    <%= f.file_field :picture, accept: 'image/jpg,image/jpeg,image/gif,image/png' %>
  </div>

  <%= submit_tag '登録', class: 'btn btn-primary' %>
<% end %>

<script type="text/javascript">
  $('#memo_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('扱えるファイルサイズは5MBまでです。');
    }
  });
</script>

app/views/memos/edit.html.erb
<div class="container">
  <h2>編集</h2>
  <%= render partial: 'form', locals: { memo: @memo } %>
</div>

app/views/memos/index.html.erb
<%= render 'shared/error_messages' %>

<div class="container">
  <h3>メモ 一覧</h3>
  <% @memos.each do |memo| %>
    <div class="col-sm-4">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <h4 class="panel-title"><%= memo.title %></h4>
          <p><%= memo.category.name %></p>

          <div class="buttons">
            <%= link_to '', edit_memo_path(memo), class: 'glyphicon glyphicon-edit' %>
            <%= link_to '', memo, class: 'glyphicon glyphicon-trash', method: :delete %>
          </div>
        </div>
        <div class="panel-body">
          <%= memo.body %>
          <%= image_tag memo.picture.url if memo.picture? %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/memos/new.html.erb
<div class="container">
  <h2>新規作成</h2>
  <%= render partial: "form", locals: { memo: @memo } %>
</div>

app/views/shared/_error_messages.html.erb
<% if flash[:error_messages] %>
  <div class="alert alert-danger">
    <ul>
      <% flash[:error_messages].each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/error_messages' %>

<%= form_with model: user do |f| %>
  <div class="form-group">
    <%= f.label :name, 'ユーザー名（20文字以内）' %>
    <%= f.text_field :name, autofocus: true, autocomplete: 'name', class: 'form-control', required: 'required' %>
  </div>
  <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.email_field :email, autocomplete: 'email', class: 'form-control', required: 'required' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード（8文字以上）' %>
    <%= f.password_field :password, autocomplete: 'new-password', class: 'form-control', required: 'required', minlength: '8' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, '確認用パスワード' %>
    <%= f.password_field :password_confirmation, autocomplete: 'new-password', class: 'form-control', required: 'required' %>
  </div>

  <%= f.submit '作成', class: 'btn btn-primary' %>
<% end %>

app/views/users/me.html.erb
<h1>マイページ</h1>
<p><%= @current_user.name %></p>
<p><%= @current_user.email %></p>

app/views/users/new.html.erb
<div class="container user-form">
  <h2>新規ユーザー登録</h2>
  <br/>
  <%= render partial: 'form', locals: { user: @user } %>
</div>